[profile.default]
src = 'contracts'
out = 'forge-out'
libs = ['lib']
solc_version = '0.8.26'
evm_version = 'cancun'
optimizer_runs = 1000000
verbosity = 2

[rpc_endpoints]
anvilGearbox = "https://anvil.gearbox.foundation/rpc/Ethereum"
